# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_bart <- function(X_con, y, Z, X_mod, X_con_test, X_mod_test, alpha, beta, alpha_tau, beta_tau, sigma_mu, sigma_tau, v_0, sigma_0, n_iter, n_tree, n_tree_tau, min_nodesize) {
    .Call(`_mvbcf_fast_bart`, X_con, y, Z, X_mod, X_con_test, X_mod_test, alpha, beta, alpha_tau, beta_tau, sigma_mu, sigma_tau, v_0, sigma_0, n_iter, n_tree, n_tree_tau, min_nodesize)
}

rcpparma_hello_world <- function() {
    .Call(`_mvbcf_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mvbcf_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mvbcf_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mvbcf_rcpparma_bothproducts`, x)
}

